### ISSUE TITLE
Getting errors when I run. 

### ISSUE THREAD

**Issue by clickbrain** [da-z/mlx-ui#1]
In UI: 
ValueError: Missing parameters: lm_head.biases lm_head.scales.
Traceback:
File "/Users/bradn/mlx-ui/venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "/Users/bradn/mlx-ui/app.py", line 58, in <module>
    model, tokenizer = load_model(model_ref)
File "/Users/bradn/mlx-ui/venv/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 212, in wrapper
    return cached_func(*args, **kwargs)
File "/Users/bradn/mlx-ui/venv/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 241, in __call__
    return self._get_or_create_cached_value(args, kwargs)
File "/Users/bradn/mlx-ui/venv/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 267, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
File "/Users/bradn/mlx-ui/venv/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 321, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
File "/Users/bradn/mlx-ui/app.py", line 55, in load_model
    return load(ref)
File "/Users/bradn/mlx-ui/venv/lib/python3.10/site-packages/mlx_lm/utils.py", line 232, in load
    model = load_model(model_path)
File "/Users/bradn/mlx-ui/venv/lib/python3.10/site-packages/mlx_lm/utils.py", line 205, in load_model
    model.load_weights(list(weights.items()))
File "/Users/bradn/mlx-ui/venv/lib/python3.10/site-packages/mlx/nn/layers/base.py", line 151, in load_weights
    raise ValueError(f"Missing parameters: {missing}.")

CLI: 
Traceback (most recent call last):█████████| 16.1G/16.1G [08:33<00:00, 56.1MB/s]
  File "/Users/bradn/mlx-ui/venv/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 264, in _get_or_create_cached_value
    cached_result = cache.read_result(value_key)
  File "/Users/bradn/mlx-ui/venv/lib/python3.10/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 498, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bradn/mlx-ui/venv/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 312, in _handle_cache_miss
    cached_result = cache.read_result(value_key)
  File "/Users/bradn/mlx-ui/venv/lib/python3.10/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 498, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bradn/mlx-ui/venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/Users/bradn/mlx-ui/app.py", line 58, in <module>
    model, tokenizer = load_model(model_ref)
  File "/Users/bradn/mlx-ui/venv/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 212, in wrapper
    return cached_func(*args, **kwargs)
  File "/Users/bradn/mlx-ui/venv/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 241, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "/Users/bradn/mlx-ui/venv/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 267, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "/Users/bradn/mlx-ui/venv/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 321, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "/Users/bradn/mlx-ui/app.py", line 55, in load_model
    return load(ref)
  File "/Users/bradn/mlx-ui/venv/lib/python3.10/site-packages/mlx_lm/utils.py", line 232, in load
    model = load_model(model_path)
  File "/Users/bradn/mlx-ui/venv/lib/python3.10/site-packages/mlx_lm/utils.py", line 205, in load_model
    model.load_weights(list(weights.items()))
  File "/Users/bradn/mlx-ui/venv/lib/python3.10/site-packages/mlx/nn/layers/base.py", line 151, in load_weights
    raise ValueError(f"Missing parameters: {missing}.")
ValueError: Missing parameters: lm_head.biases lm_head.scales.

**Comment by da-z** [comment]
Hi. Thanks for letting me know.

Looks like there is a breaking change in mlx. I updated the install.sh script to use requirements.txt from repo for now. 

To fix the issue you can just git pull then run `./install.sh` again and then `./run.sh` (if you are already in the venv, run `deactivate` first)

**Comment by da-z** [comment]
I will close this issue given a work-around has been provided. There will be an update later on after `mlx-lm` 0.0.5 release.

**Comment by clickbrain** [comment]
Thank you!

**Comment by clickbrain** [comment]
Just a heads up. I updated with the pull and still getting same error message. 

Meant to tell you, that I really appreciate you creating this. Thanks.

**Comment by da-z** [comment]
Ah yes, you must reset your local requirements.txt too. And thank you :)

```
$ git restore requirements.txt
./install.sh
```

**Comment by clickbrain** [comment]
That did the trick!  Thanks for the fast response.

**Comment by da-z** [comment]
You're welcome ☺️
